### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by aoliliao** [TsingZ0/PFL-Non-IID#101]
您好，我参考了您的代码，但是结果没有办法复现，只有开头前2个epoch可以复现，不知道是什么原因。我修改了数据的读取方式，直接读取数据然后生成DataLoader传给client，想问一下这样的改变会造成结果不能复现吗？谢谢

**Comment by TsingZ0** [comment]
可否提供更多细节？比如：哪些方法、超参数设置等信息

**Comment by aoliliao** [comment]
好的，我重新说明一下问题。我使用FedBN这篇文章提供的数据集和AlexNet进行测试，但是FedAvg和FedBN的结果几乎相同。AlexNet是有包含bn层的，超参数也基本和文章一样，请问问题可能出在哪？

**Comment by TsingZ0** [comment]
AlexNet是没有bn层的，请查阅google。

注：本平台的目的并不是复现论文结果，而是为大家提供一个统一的平台，发现各个算法的不足，找到新的idea。复现结果是作者官方代码的义务
