### ISSUE TITLE
FedPHP optimizer doesn't work

### ISSUE THREAD

**Issue by zingjk** [TsingZ0/PFL-Non-IID#102]
the parameters is 
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/88484504/30498778-13fc-4e80-8c2c-7479ba673829)
but the result is 
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/88484504/7878a4ff-590f-4741-a5af-b523c89e8853)
help!

**Comment by TsingZ0** [comment]
You may need to set reasonable hyperparameters `-mu` and `lam`, e.g., `-mu 0.9 -lam 1e-2`, for FedPHP.

**Comment by zingjk** [comment]
> You may need to set reasonable hyperparameters `-mu` and `lam`, e.g., `-mu 0.9 -lam 1e-2`, for FedPHP.

Thanks! I have a new question, what hyperparameters should be set about pFedMe?

**Comment by TsingZ0** [comment]
According to its paper and my tuning experiments, `-lrp 0.01 -bt 3 -lam 15` is suitable for pFedMe.

**Comment by zingjk** [comment]
Thanks！



发自我的iPhone


------------------ Original ------------------
From: Tsing ***@***.***&gt;
Date: Fri,Jul 7,2023 11:20 AM
To: TsingZ0/PFL-Non-IID ***@***.***&gt;
Cc: zingjk ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TsingZ0/PFL-Non-IID] FedPHP optimizer doesn't work (Issue #102)
