### ISSUE TITLE
FedProto的一个问题

### ISSUE THREAD

**Issue by MirandaHe** [TsingZ0/PFL-Non-IID#104]
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/105597549/4928f65d-fb75-4803-82f1-ec7298b299ad)

使用FedProto时，用TextCNN训练agnews时，每轮训练的精度都保持不变，没太弄懂原因，请教一下

**Comment by TsingZ0** [comment]
采用不同的model会有不同的情况，有时候会在前几轮都没有精度，但之后精度会上升。第100轮也还是这个精度吗？可以看看TextCNN在中心化训练时是不是也有这种情况。具体model特性的研究不在联邦学习的范畴之内
