### ISSUE TITLE
传统机器学习数据集

### ISSUE THREAD

**Issue by bo2698** [TsingZ0/PFL-Non-IID#105]
很佩服大佬的工作，不知大佬能否写一个iris数据集处理的代码generate_iris.py，自己写的能够生成数据，但是会报错。
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by TsingZ0** [comment]
平台中没有提供的数据集和联邦学习算法，请根据README.md指引自行添加 :-)
