### ISSUE TITLE
关于clientperavg中的学习率问题

### ISSUE THREAD

**Issue by TigerAB1** [TsingZ0/PFL-Non-IID#106]
您好，我最近也是在学习您写代码，在这里我有些问题想向您请教一下。就是在clientperavg中为什么 self.beta = self.learning_rate，而不是直接self.beta = args.beta？

**Comment by TsingZ0** [comment]
因为在实际运行代码的时候，我发现self.beta = self.learning_rate这种取值比较适合大部分settings和datasets，所以默认是self.beta = self.learning_rate，省去了这部分的超参数调整。如果要自己去调beta，您可以对self.beta = args.beta这行取消注释

**Comment by TigerAB1** [comment]
> 
明白了，谢谢
