### ISSUE TITLE
关于peravg中的FO和HF问题

### ISSUE THREAD

**Issue by TigerAB1** [TsingZ0/PFL-Non-IID#107]
您好，首先非常感谢您的开源精神和贡献，我在学习您的关于peravg的时候并没有发现将海森矩阵忽略进行一阶近似的Per-FedAvg(FO）和Hessian向量积使用HF方法进行替代的Per-FedAvg(HF）的代码，是没有嘛？如果我想使用Per-FedAvg(FO）和Per-FedAvg(HF），我该怎么去改呢？如果您百忙之中能够抽出时间给我提出一点意见，我将不胜感激！

**Comment by TsingZ0** [comment]
我们这边主要复现的是Per-FedAvg(FO）版本，这也是其他论文用作对比方法时，较为通用的版本。我们这里就是用了一阶近似

**Comment by TigerAB1** [comment]
好的，感谢您的回答
