### ISSUE TITLE
请求将聚类联邦学习算法（CFL）集成到框架

### ISSUE THREAD

**Issue by syq1175554320** [TsingZ0/PFL-Non-IID#108]
感谢您提供的集成框架，对我的学习帮助很大，如果可以，请求您集成一些有关个性化联邦学习中的一些聚类联邦学习算法。

**Comment by TsingZ0** [comment]
由于我个人时间有限，所以基本上复现的都是我自己做论文用得到的方法，目前不涉及个性化聚类联邦学习算法。

这个平台的一大优点就是方便拓展，您可以根据[Easy-to-extend](https://github.com/TsingZ0/PFL-Non-IID#easy-to-extend)说明去拓展平台😁

**Comment by syq1175554320** [comment]
好的，感谢您

**Comment by polaris-973** [comment]
@syq1175554320 您好，请问您这边是否有搜索到此类CFL算法可供移植的源代码？
