### ISSUE TITLE
Some issue about FedProx

### ISSUE THREAD

**Issue by gpx333** [TsingZ0/PFL-Non-IID#112]
In ths clientprox.py,  is there a problem with the calculation of loss in lines 47-49,? Shouldn't we use the loss calculation method in lines 82-86?

**Comment by yokinglee718** [comment]
Hello, for algorithms like FedProx and SCAFFOLD, the special optimizer they use is not as effective as the Adam optimizer I used in other algorithms. Can this be used as a comparative experiment？

**Comment by TsingZ0** [comment]
Sure, you can adopt any optimizer as you want by modifying their codes and study whether other optimizers are more suitable.
