### ISSUE TITLE
Why Accuracy metric is different ?

### ISSUE THREAD

**Issue by ajulyav** [TsingZ0/PFL-Non-IID#115]
Hello,

I have the results of my training as:
```

Evaluate global model
Averaged Train Loss: 1.1409
Averaged Test Accurancy: 0.7814
Averaged Test AUC: 0.9318
Std Test Accurancy: 0.4208
Std Test AUC: 0.1784
```

but when I take this saved model and inference on each client, I get different values:
like client 1 acc: 0.683
client 2 acc: 0.435
client 3: 0.664

I tested with different models and does not work. I am expecting that they (client1+client2+client3)/3 should give me 0.78 but it does never happen. 

What could be a problem?

**Comment by TsingZ0** [comment]
Sorry for the delayed response. I have been quite busy recently and couldn't reply to your message in a timely manner.

I notice that the std of clients' accuracy is very high. Did you only use three clients in total? The test is performed on all clients rather than only the participating clients.

**Comment by TsingZ0** [comment]
Can you show the command line you used for running the experiment?

**Comment by ajulyav** [comment]
Sure, for example:

python main.py -go resnet -dev "cuda" -data noniid_clients02 -nb 8 -m resnet -lbs 10 -lr 0.001 -algo FedAvg -gr 10 -ls 5 -nc 2

**Comment by TsingZ0** [comment]
This command line shows that you only used two clients, as `-nc=2`. 

As reproducing your situation without the `noniid_clients02` data is difficult, I evaluated it on my setting where the issue you mentioned did not occur. Note that the test accuracy is a weighted average of clients' accuracy. 

```
-------------Round number: 10-------------

Evaluate performance
Client 0: Acc: 0.14931506849315068, AUC: 0.9144203990491018
Client 1: Acc: 0.13538461538461538, AUC: 0.9235255552912491
Client 2: Acc: 0.12868852459016394, AUC: 0.8563372830289583
Client 3: Acc: 0.07883211678832117, AUC: 0.9013049396377165
Client 4: Acc: 0.12785714285714286, AUC: 0.9237237193621166
Client 5: Acc: 0.05827338129496403, AUC: 0.866120327843867
Client 6: Acc: 0.10071942446043165, AUC: 0.9281595337590598
Client 7: Acc: 0.07737226277372262, AUC: 0.8856186186941956
Client 8: Acc: 0.13478260869565217, AUC: 0.888807209487893
Client 9: Acc: 0.07166666666666667, AUC: 0.8578753105806813
Client 10: Acc: 0.12056737588652482, AUC: 0.8897290941402854
Client 11: Acc: 0.09927536231884058, AUC: 0.8990863448728625
Client 12: Acc: 0.08633093525179857, AUC: 0.9237746935599274
Client 13: Acc: 0.13401360544217686, AUC: 0.9089713863872559
Client 14: Acc: 0.10218978102189781, AUC: 0.9000250493235531
Client 15: Acc: 0.14469696969696969, AUC: 0.8626746911785743
Client 16: Acc: 0.12753623188405797, AUC: 0.8811193332763376
Client 17: Acc: 0.08333333333333333, AUC: 0.7887194472071003
Client 18: Acc: 0.12028985507246377, AUC: 0.8929536453006472
Client 19: Acc: 0.10425531914893617, AUC: 0.9186549251968812
Averaged Test Accurancy: 0.1094
Averaged Test AUC: 0.8909
Std Test Accurancy: 0.0260
Std Test AUC: 0.0322
```
