### ISSUE TITLE
为什么alpha = 0.1得到的测试精确度比a=1的要高

### ISSUE THREAD

**Issue by Wangyue2333** [TsingZ0/PFL-Non-IID#119]
我的超参数是：-lr 0.1 -ldg 0.998 -lbs 16 -nc 20 -jr 1 -nb 10

**Comment by Wangyue2333** [comment]
alpha=1时，准确度基本在0.64左右徘徊，但是当alpha=0.1时，仅仅在260个epoch时就已经到了0.7。这显然是违反常识的，我使用的是Cifar10数据集、Fedavg算法、Resnet网络。请原谅我是个新手，谢谢大哥的回复！

**Comment by YakultGo** [comment]
同样遇到了问题，在cifar10和cifar100上面，alpha越大，反而效果越差不知道为啥
