### ISSUE TITLE
在peravg中的问题

### ISSUE THREAD

**Issue by TigerAB1** [TsingZ0/PFL-Non-IID#120]
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/116572728/5ee7e725-2523-4de4-8cd4-239249f7fd12)
您好，我的超参数在以上情况的时候，出现以下报错，请问为什么呢？
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/116572728/c96e3599-b2c1-4b34-bb63-5bf43ac90f32)

**Comment by TigerAB1** [comment]
您好，大佬，上面问题我已经知道原因，当我为了解决这个问题，而在generate_mnist.py里面尝试将batch_size改成40时，我发现这样会导致least_samples太大，从而导致用狄利克雷来分的时候一直处于运行中（没有结果），我是否应该直接将least_samples改成为40，但是我不知道我这样改会不会影响到其他地方，希望您百忙之中能够指教。

**Comment by TsingZ0** [comment]
您好，我这边在generate_mnist.py里面尝试将batch_size改成40时，代码运行没有问题

**Comment by TigerAB1** [comment]
> 您好，我这边在generate_mnist.py里面尝试将batch_size改成40时，代码运行没有问题

能问一下您使用的参数是多少吗？我使用的是num_clients = 100，batch_size = 40
train_size = 0.75 
least_samples = batch_size / (1-train_size) 
alpha = 0.1，你最后运行成功用了多久啊？运出来快吗

**Comment by TigerAB1** [comment]
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/116572728/2f8578ec-2958-40f8-88af-78c26f535eb9)
运行了40分钟，没结果啊

**Comment by TsingZ0** [comment]
更新了一下代码，请查看
