### ISSUE TITLE
正确率一直不变

### ISSUE THREAD

**Issue by lgwy** [TsingZ0/PFL-Non-IID#124]
您好，非常感谢您的分享。
我按照readme运行您的代码，使用lstm模型和agnews数据集做词法分析，为什么正确率是个常数呢？就是正确率从始至终都是0.306。之后我添加了mlp模型，数据集是我自己的csv文件，改代码跑通后正确率也是从始至终不变。希望您能指点一二，万分感谢。

**Comment by TsingZ0** [comment]
联邦学习系统的运行涉及诸多细节，请问能否提供你遇到的问题的更多细节？

此外，根据我的经验，词法分析的实验，偶尔也会出现，前几轮准确率不变的情况，之后则会逐步上升。你指的“正确率从始至终都是0.306”是跑了几轮呢？
