### ISSUE TITLE
FedProto

### ISSUE THREAD

**Issue by bowuhub** [TsingZ0/PFL-Non-IID#125]
clientproto.py，test_metrics中为什么
output = float('inf') * torch.ones(y.shape[0], self.num_classes).to(self.device)。
初始化为inf会造成auc计算异常（不到二成，二acc有九成）

**Comment by TsingZ0** [comment]
跟据FedProto原文，它采用prototype-based model inference，也就是取距离最小的为对应的class。我们这里，`output` 是用于计算距离的，理应初始化为inf。

你描述的“初始化为inf会造成auc计算异常（不到二成，二acc有九成）”，我没看懂，能否提供更多细节？
