### ISSUE TITLE
使用resnet出现的问题

### ISSUE THREAD

**Issue by TigerAB1** [TsingZ0/PFL-Non-IID#130]
1、您好，当我用以下超参时
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/116572728/61acb0e9-2449-4e61-954d-371556090431)
会出现以下报错
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/116572728/52e4f5af-0ada-4f5e-b42c-ca77746ec575)
并且我发现即使我用cnn，我的GPU占用显存，在每进行一个epoch的时候，都会慢慢增加这是为什么？
2、而且在Dirichlet中您将代码改成min_size < num_classes:的时候，当在类别少的数据集时，可以分出来。但是类别多的时候，只要客户端一多，比如500个客户端，alpha为0.3，数据集为cifar100的时候，还是陷入一个死循环，导致数据无法分出来。

**Comment by TsingZ0** [comment]
只参与过FL的客户机会才会保留一些backpropagation所需的中间变量到显存。由于你设置了Clients join in each round < 1，那么在刚开始的几轮，参加过FL的客户机会逐渐增加，显存也会逐渐增加，直到所有500个客户机都参与过FL，才会停止增加显存。如果你每一轮选择客户机采用的是随机选择，那显存的增加在哪一个communication round停下也就不可预估。

数据生成代码已更新。

**Comment by TigerAB1** [comment]
> 只参与过FL的客户机会才会保留一些backpropagation所需的中间变量到显存。由于你设置了Clients join in each round < 1，那么在刚开始的几轮，参加过FL的客户机会逐渐增加，显存也会逐渐增加，直到所有500个客户机都参与过FL，才会停止增加显存。如果你每一轮选择客户机采用的是随机选择，那显存的增加在哪一个communication round停下也就不可预估。
> 
> 数据生成代码已更新。

好的，感谢您的回答，我还要疑问想请教您，就是我使用上面我所述的超参（即500客户端resnet）的时候直接会出现上面的报错是怎么回事啊？该怎么去解决呢？

**Comment by TsingZ0** [comment]
很抱歉上次回复漏掉了第一个问题。这个情况我没遇到过，[可能是CUDA版本的问题](https://stackoverflow.com/questions/75776895/runtimeerror-get-was-unable-to-find-an-engine-to-execute-this-computation-when)

**Comment by TigerAB1** [comment]
> 很抱歉上次回复漏掉了第一个问题。这个情况我没遇到过，[可能是CUDA版本的问题](https://stackoverflow.com/questions/75776895/runtimeerror-get-was-unable-to-find-an-engine-to-execute-this-computation-when)
没事，您有试过500客户端去使用resnet-18吗，我用了之后我的gpu显存直接不够，gpu显存一直上涨直到把显存占完之后就出现上面报错，我100个客户端就没事（我用的是3090），有没有可能是客户端太多的原因呢

**Comment by TigerAB1** [comment]
> 很抱歉上次回复漏掉了第一个问题。这个情况我没遇到过，[可能是CUDA版本的问题](https://stackoverflow.com/questions/75776895/runtimeerror-get-was-unable-to-find-an-engine-to-execute-this-computation-when)

没事，您有试过500客户端去使用resnet-18吗，我用了之后我的gpu显存直接不够，gpu显存一直上涨直到把显存占完之后就出现上面报错，我100个客户端就没事（我用的是3090），有没有可能是客户端太多的原因呢

**Comment by TsingZ0** [comment]
是的，如果用resnet-18跑500个客户端的话，会显存不够的，这时候可以考虑用PyTorch的数据或模型并行

**Comment by TigerAB1** [comment]
> 是的，如果用resnet-18跑500个客户端的话，会显存不够的，这时候可以考虑用PyTorch的数据或模型并行
很感谢您回答，我是个小白，如果我想在您的代码中，让它进行模型并行，使用两块gpu我该怎么改，您能给我点建议吗？

**Comment by TigerAB1** [comment]
> 是的，如果用resnet-18跑500个客户端的话，会显存不够的，这时候可以考虑用PyTorch的数据或模型并行

感谢您的回答，我是个小白，如果我想在您的代码中实行模型并行，使用两块GPU，我该怎么改呢，您这边能给我点建议吗？

**Comment by TsingZ0** [comment]
可以google搜索“pytorch ddp”，可以参考[这个教程](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html)
