### ISSUE TITLE
perFedAvg相关问题

### ISSUE THREAD

**Issue by gitCoder1024** [TsingZ0/PFL-Non-IID#132]
很感谢仓库开源的代码。在perFedAvg算法的实现中，client端的train方法已经进行了step 1和step 2的train，为什么server端还需要再train方法中两次调用client.train()呢？

**Comment by gitCoder1024** [comment]
而且trainloader每次返回的不就是batch_size大小的数据吗，在client端进行step 2时有数据可用吗

**Comment by TsingZ0** [comment]
Please refer to #59.
