### ISSUE TITLE
生成数据的相关问题

### ISSUE THREAD

**Issue by OUCLJW** [TsingZ0/PFL-Non-IID#133]
IndexError: list index out of range**
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/148048044/310ab8e7-5457-48d1-9c20-832b1cbccc33)
**
博主您好请问此类问题应该如何解决0.0

**Comment by isaacveg** [comment]
python命令后面必须跟上是否是noniid，划分是否balance和划分方式pat或dir
`python generate_cifar100.py noniid balance pat`
