### ISSUE TITLE
question about aggregate_parameter function at server_base.py

### ISSUE THREAD

**Issue by rachel618** [TsingZ0/PFL-Non-IID#138]
I have a question about aggregate_parameter function at server_base.py 

why is this necessary?
`self.global_model = copy.deepcopy(self.uploaded_models[0])`
You already deepcopy global model to client model.
When I implemented this code removing that line, average train losses decreased after a few epochs but test accuracy remained unchanged.

**Comment by rachel618** [comment]
I saw #43 but I sill have a question.
You already initialized the global model at init() , and client and model architectures are same.
I want to get difference between global model parameters before aggregating parameters and after aggregating parameters.
In my case, the global model parameters should not be changed before aggregate_parameters() , but the code overwrite global model parameters by copy.deepcopy(uploaded_models[0])

**Comment by TsingZ0** [comment]
Removing the line you mentioned doesn't impact the results for `FedAvg`. Have you made any other changes or used different algorithms?
