### ISSUE TITLE
是否考虑一下加入和Transformer有关的pFL？

### ISSUE THREAD

**Issue by Changee-git** [TsingZ0/PFL-Non-IID#143]
作者您好，最近研究个性化联邦学习的时候我发现出现了将CNN替换为Transformer的个性化算法，比如FedTP（一区），不知道您是否有意向将此类似的算法模型整合进来呢？

**Comment by TsingZ0** [comment]
本平台对于模型结构没有要求，可在`main.py`中任意替换
