### ISSUE TITLE
Cifar100的测试问题

### ISSUE THREAD

**Issue by LLYYKK** [TsingZ0/PFL-Non-IID#145]
仿照Cifar10的数据及生成方式生成Cifar100的数据，运行main.py会报以下错误。
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

**Comment by TsingZ0** [comment]
这个是因为`sklearn.metrics.roc_auc_score()`方法不支持只有一个类的数据。

能否检查一下，是不是设置的data heterogeneity过于夸张，导致某个client只有一个类的数据？

**Comment by tjut-edu** [comment]
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.这个问题是由于只在运行语句里改为了Cifar100，但是没有把代码里class_number改成100，所以报这个错。
