### ISSUE TITLE
Questions about GPFL parameters

### ISSUE THREAD

**Issue by GerrysHazzah** [TsingZ0/PFL-Non-IID#147]
About GPFL It is indeed a great algorithm, but when I tried to reproduce it, even though I tried many sets of parameters, there was still a situation where the loss value converged around 3, so I'm sorry to bother you, I wonder if you can share the relevant experimental parameters.
I wish you a happy life and smooth work

**Comment by TsingZ0** [comment]
Thank you for your attention to our GPFL algorithm! 

If you want to reproduce it, please refer to its [official code](https://github.com/TsingZ0/GPFL). I also provide the hyperparameter setting in https://github.com/TsingZ0/GPFL/issues/6

Please note that the results obtained on this platform may vary and may not align with the results presented in our paper without re-tuning hyperparameters. We frequently update this platform's basic settings, which can affect the outcomes.
