### ISSUE TITLE
如何评价算法的隐私保护能力

### ISSUE THREAD

**Issue by FryLcm** [TsingZ0/PFL-Non-IID#148]
您好，我想像您请教一下，如果我每隔100轮进行一次梯度泄露攻击，在1000轮中我可以得到10个PSNR指标。请问在这10个PSNR指标中，我该以哪个来体现算法隐私保护能力？是取这十个中PSNR值最大的那个吗？

**Comment by TsingZ0** [comment]
一般是取一个能让所有algorithms收敛的足够大的通讯轮数，比较在该轮数下的PSNR指标。

**Comment by FryLcm** [comment]
> 一般是取一个能让所有算法收敛的足够大的通讯轮数，比较在该轮数下的PSNR指标。

正如你说的这样，我选取通讯轮数为1000轮，每隔100轮得到一个PSNR指标，那么我就可以得到10个PSNR指标。该使用这10个中的哪个来评价隐私保护能力？是这十个PSNR指标中值最大的那个吗？

**Comment by TsingZ0** [comment]
一般是使用最后一个

**Comment by FryLcm** [comment]
> 一般是使用最后一个

十分感谢您的回复。
