### ISSUE TITLE
FedAmp中与论文公式不符

### ISSUE THREAD

**Issue by lipei246** [TsingZ0/PFL-Non-IID#15]
函数A需要满足A(0)=0，代码中函数e为math.exp(-x/self.sigma)/self.sigma   self.sigma默认为1，所以e(0)=1不符合论文，应调整为1-math.exp(-x/self.sigma)/self.sigma

**Comment by lipei246** [comment]
![image](https://user-images.githubusercontent.com/62500787/176178516-a53e82b8-d304-4b48-9bdb-7bad591120b4.png)
![image](https://user-images.githubusercontent.com/62500787/176178546-8bc6b51c-a924-412f-a84f-2c881d4e1015.png)

**Comment by lipei246** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/62500787/176179963-e1412cdf-0472-4271-923a-8ef477f7c105.png">

**Comment by TsingZ0** [comment]
Hi, @lipei246 

> 函数A需要满足A(0)=0，代码中函数e为math.exp(-x/self.sigma)/self.sigma self.sigma默认为1，所以e(0)=1不符合论文，应调整为1-math.exp(-x/self.sigma)/self.sigma

`e()` is the derivative of A() in the paper, i.e. A'(). 


> 在计算自己客户端的权重（coef_self）时，是否应该使用1-torch.sum(coef). 我们在计算每一个coef[j]的时候并没有进行归一化那是否可以使用1进行减法。

I write the code `coef_self = 1 - torch.sum(coef)` based on the Equation (5) in *Personalized Cross-Silo Federated Learning on Non-IID Data*.

**Comment by lipei246** [comment]
![image](https://user-images.githubusercontent.com/62500787/176615586-4f69467c-dcb7-431c-a8fb-4d3a5d0485b0.png)
So have you left this part of the formula?

**Comment by lipei246** [comment]
![image](https://user-images.githubusercontent.com/62500787/176616085-c883adce-14e5-45cc-88f7-124e8087dca6.png)

**Comment by lipei246** [comment]
![image](https://user-images.githubusercontent.com/62500787/176616194-883e2df2-7a11-47ea-95ff-5c03f31b1e2c.png)
So have you left this part of the formula?

**Comment by lipei246** [comment]
![image](https://user-images.githubusercontent.com/62500787/176616501-11b5c598-379c-4855-b8ed-9909a17e1a4a.png)
So have you left this part of the formula?

**Comment by lipei246** [comment]
![image](https://user-images.githubusercontent.com/62500787/176625716-3ce5600f-8351-4b18-8312-fe342edd68fe.png)
第一个蓝色箭头部分如果是作者所说的是根据公式五所写这一说法确实没问题，但是我认为你少了一部分你只写了前半部分然而没写后半部分公式五的第二行还有后半部分公式，才能构成完整的公式五。所以我认为我的图中的红色箭头是作者写的并完美的表示了公式五的第二种表达方式（第二个等号）。  
此外我认为图中的蓝色箭是更新下一轮次的本地客户端模型的代码，作者为什么要将coef_self传入？这部分在clientamp中的代码我认为不符合公式六的更新本地客户端的数学公式呀。
以上都是我个人见解，希望得到真诚的解答，并永远尊重作者，希望得到解答！

**Comment by lipei246** [comment]
第一个蓝色箭头部分如果是作者所说的是根据公式五所写这一说法确实没问题，但是我认为你少了一部分你只写了前半部分然而没写后半部分公式五的第二行还有后半部分公式，才能构成完整的公式五。所以我认为我的图中的红色箭头是作者写的并完美的表示了公式五的第二种表达方式（第二个等号）。  
此外我认为图中的蓝色箭是更新下一轮次的本地客户端模型的代码，作者为什么要将coef_self传入？这部分在clientamp中的代码我认为不符合公式六的更新本地客户端的数学公式呀。
以上都是我个人见解，希望得到真诚的解答，并永远尊重作者，希望得到解答！

**Comment by lipei246** [comment]
![1656577115092](https://user-images.githubusercontent.com/62500787/176629437-9943478a-bc89-4ae1-ab3c-fc088a39c810.jpg)

**Comment by lipei246** [comment]
我刚大学二年级请原谅我的知识浅薄
