### ISSUE TITLE
Question about balanced Dirichlet distribution

### ISSUE THREAD

**Issue by zhmzm** [TsingZ0/PFL-Non-IID#18]
```
for k in range(K):
                idx_k = np.where(dataset_label == k)[0]
                np.random.shuffle(idx_k)
                proportions = np.random.dirichlet(np.repeat(alpha, num_clients))
                ## Balance
                proportions = np.array([p*(len(idx_j)<N/num_clients) for p,idx_j in zip(proportions,idx_batch)])
                proportions = proportions/proportions.sum()
                proportions = (np.cumsum(proportions)*len(idx_k)).astype(int)[:-1]
                idx_batch = [idx_j + idx.tolist() for idx_j,idx in zip(idx_batch,np.split(idx_k,proportions))]
                min_size = min([len(idx_j) for idx_j in idx_batch])
```
Hi,
how can I make the number of samples in each client balanced? Thank you for your reply.

**Comment by Yutong-Dai** [comment]
> ```
> for k in range(K):
>                 idx_k = np.where(dataset_label == k)[0]
>                 np.random.shuffle(idx_k)
>                 proportions = np.random.dirichlet(np.repeat(alpha, num_clients))
>                 ## Balance
>                 proportions = np.array([p*(len(idx_j)<N/num_clients) for p,idx_j in zip(proportions,idx_batch)])
>                 proportions = proportions/proportions.sum()
>                 proportions = (np.cumsum(proportions)*len(idx_k)).astype(int)[:-1]
>                 idx_batch = [idx_j + idx.tolist() for idx_j,idx in zip(idx_batch,np.split(idx_k,proportions))]
>                 min_size = min([len(idx_j) for idx_j in idx_batch])
> ```
> 
> Hi, how can I make the number of samples in each client balanced? Thank you for your reply.

This implementation considers per class-label follows a Dirichlet distribution on all clients, which means you have no way to guarantee each clients have the same number of samples.

What you can do is first set the number of sample on each client. And For each client, force the class label distribution to  follow a Dirichlet distribution.

**Comment by lipei246** [comment]
![image](https://user-images.githubusercontent.com/62500787/176829714-e2965c01-281c-40fe-8c36-cb4ae5a16393.png)
FEDAMP论文中所说迪利克雷分布的Non-IID中每个客户端包含所有的类别，那我应该如何更改？，我看作者的划分的数据集中并不是一个客户端包含所有的类别。

**Comment by zhmzm** [comment]
> 

Thanks a lot!
