### ISSUE TITLE
关于结果输出的代码在哪里

### ISSUE THREAD

**Issue by lipei246** [TsingZ0/PFL-Non-IID#19]
-------------Round number: 3-------------

Evaluate global model
Averaged Train Loss: 0.6725
Averaged Test Accurancy: 0.8453
Averaged Test AUC: 0.9514
Std Test Accurancy: 0.1707
Std Test AUC: 0.0432

我没有找到这些语句是在哪里输出的。eg,Train loss和Test Accurancy

**Comment by lipei246** [comment]
我想进行修改，先训练收敛之后在使用测试集测试，应该如何修改呢？而不是训练一次验证一次

**Comment by TsingZ0** [comment]
Please check `evaluate()` in `serverbase.py`
