### ISSUE TITLE
Test accuracy are very different 

### ISSUE THREAD

**Issue by CityChan** [TsingZ0/PFL-Non-IID#22]
For cifar10 dataset, some methods such as Fedproto, pFedMe, Fedper can achieve nearly 90% but for FedAvg, Fedprox and FedBN can only achieve about 35%. Are they using different test dataset? For personalized methods, you are using local testdata (with similar data distribution) and for non-personalized methods, you are using a global testdata.

**Comment by TsingZ0** [comment]
For FedBN, as it requires the batch normalization (BN) layer in the model, its performance is similar with FedAvg when using the built-in four-layer CNN. You need to use the ResNets for FedBN.

**Comment by CityChan** [comment]
> For FedBN, as it requires the batch normalization (BN) layer in the model, its performance is similar with FedAvg when using the built-in four-layer CNN. You need to use the ResNets for FedBN.

For fedavg, I found the local training(with transmitting model) test accurracy is much better than fedavg( transmitting model parameters). Is that reasonable?

**Comment by CityChan** [comment]
> For FedBN, as it requires the batch normalization (BN) layer in the model, its performance is similar with FedAvg when using the built-in four-layer CNN. You need to use the ResNets for FedBN.

It is not just the problem of FedBN. Some personalized federated learing  methods have the similar results to local training(without any interaction among clients). For example, for cifar10 dataset, Fedproto, FedRep, pFedMe,FedPer  and Local training can achieve 88-89% test accuracy but fedavg, fedprox achieve 35%.

**Comment by TsingZ0** [comment]
> for non-personalized methods, you are using a global testdata.

The test data setting is the same among all the algorithms in this platform, please check it again :-). Following pFedMe ([Personalized Federated Learning with Moreau Envelopes](https://proceedings.neurips.cc/paper/2020/file/f4f1f13c8289ac1b1ee0ff176b56fc60-Paper.pdf)), I evaluate the global model for the traditional federated learning (FL) methods (fedavg, fedprox, feddyn, moon, etc.) and evaluate the personalized (local) model for personalized FL methods. 

> For fedavg, I found the local training(with transmitting model) test accurracy is much better than fedavg( transmitting model parameters). Is that reasonable?

Do you mean "local training(without transmitting model)"? 

> It is not just the problem of FedBN. Some personalized federated learing methods have the similar results to local training(without any interaction among clients). For example, for cifar10 dataset, Fedproto, FedRep, pFedMe,FedPer and Local training can achieve 88-89% test accuracy but fedavg, fedprox achieve 35%.

In [FedRoD](https://arxiv.org/pdf/2107.00778.pdf), it says _It is worth noting that the local models from generic FL methods are highly competitive to or even outperform personalized models produced by personalized FL methods_. With statistical heterogeneity, the global models learned by the traditional FL methods suffer poor generalization on the clients. This is why personalized FL comes into being.
