### ISSUE TITLE
about the per-fedavg

### ISSUE THREAD

**Issue by Bhongcheng** [TsingZ0/PFL-Non-IID#23]
Why the batch_size need to * 2? 
![image](https://user-images.githubusercontent.com/90205287/178980643-054cd85a-317b-4ec7-82c5-174c8c71a0aa.png)
Thank you!

**Comment by Bhongcheng** [comment]
besides, after I run the Per-fedavg algorithm, I find the average test accuracy is only about 0.1(cnn, mnist)........

**Comment by Bhongcheng** [comment]
I would appreciate it if you can help me, thanks!

**Comment by TsingZ0** [comment]
Hi @Bhongcheng, could you provide your hyperparameter setting?

**Comment by Bhongcheng** [comment]
> Hi @Bhongcheng, could you provide your hyperparameter setting?
![image](https://user-images.githubusercontent.com/90205287/179454228-e030c01c-d518-4f7a-ab03-0e94118e2a80.png)
![image](https://user-images.githubusercontent.com/90205287/179454252-c251f5ab-08b5-4203-9556-bef9cd936f1f.png)
Thanks for your reply!

**Comment by ADAM0064** [comment]
Hello, have you found out the reason? I'm working with a similar algorithm, and I've encountered a low accuracy problem like this.

> besides, after I run the Per-fedavg algorithm, I find the average test accuracy is only about 0.1(cnn, mnist)........

**Comment by Bhongcheng** [comment]
> Hello, have you found out the reason? I'm working with a similar algorithm, and I've encountered a low accuracy problem like this.
> 
> > besides, after I run the Per-fedavg algorithm, I find the average test accuracy is only about 0.1(cnn, mnist)........

No.... I am very poor in federated learning and programming

**Comment by FryLcm** [comment]
> > Hi @Bhongcheng, could you provide your hyperparameter setting?
> > ![image](https://user-images.githubusercontent.com/90205287/179454228-e030c01c-d518-4f7a-ab03-0e94118e2a80.png)
> > ![image](https://user-images.githubusercontent.com/90205287/179454252-c251f5ab-08b5-4203-9556-bef9cd936f1f.png)
> 
> besides, this is the dataset setting
> 
> "num_clients":20,"num_classes":10,"non_iid":true,"balance":false,"partition":"dir" *** "alpha":0.1,"batch_size":10
> 
> Thanks for your reply!

请问你现在了解了怎么运行per-fedavg算法吗？相比于fedavg算法，我只需要多加一个 -bt 0.001 就可以吗？我看原论文还要一个τ=10的参数？
