### ISSUE TITLE
Other values that can be passed for argument goal.

### ISSUE THREAD

**Issue by azalahmadkhan** [TsingZ0/PFL-Non-IID#24]
parser.add_argument('-go', "--goal", type=str, default="test", 
                        help="The goal for this experiment")

Hi, I wanted to know the other values that can be passed for the argument goal other than the default test?

**Comment by TsingZ0** [comment]
Hi, @azalahmadkhan, this argument is only for distinguishing the file names to save the results. You can use any value you want.
