### ISSUE TITLE
May I ask one question about FL?

### ISSUE THREAD

**Issue by Bhongcheng** [TsingZ0/PFL-Non-IID#26]
After running the code, I find that just using Local way to train the model is much better than Fedavg. So I wonder whether it is better to use FL instead of just training local model?  
    Thanks for your excellent job! Your code really helps me a lot.

**Comment by TsingZ0** [comment]
Hi, @Bhongcheng 

This phenomenon does exist in the settings, where the local data amount is sufficient for local model training. In our simulation platform, if you set the number of clients small, such as 20, the local data amount is large on each client, and this phenomenon appears. You can increase the client amount (for example 1000 clients), which will result in the local data amount decreasing. Then, you will find that this phenomenon disappears. 

Federated learning is worthy when the clients suffer from insufficient data for model training. The adequacy of the data also depends on the tasks, models, etc.

**Comment by Bhongcheng** [comment]
Thank you very much!
