### ISSUE TITLE
 from opacus.dp_model_inspector import DPModelInspector

### ISSUE THREAD

**Issue by qq648545022** [TsingZ0/PFL-Non-IID#27]
i wonder what you gays version of opacus,cause when i used the code like this ->from opacus.dp_model_inspector import DPModelInspector , it raises the problem ->ModuleNotFoundError: No module named 'opacus.dp_model_inspector'

**Comment by TsingZ0** [comment]
Hi, @qq648545022 
I mentioned "By using the package [opacus v0.15](https://github.com/pytorch/opacus/releases/tag/v0.15.0)" in the README.md, please check it.

**Comment by qq648545022** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by qq648545022** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
