### ISSUE TITLE
about the FedDyn

### ISSUE THREAD

**Issue by Mangata1** [TsingZ0/PFL-Non-IID#29]
Hello, @TsingZ0.
Thank you very much for your nice code. When I read your code, I noticed that the FedDyn implementation was not the same as the pseudo-code in the paper. Specifically you can see the figure. 
Interestingly, I reproduced the pseudo-code from the paper and found the performance to be poor, but with your approach the performance is good. I wonder if this is because the author's pseudo-code is wrong.
Thank you again for your selfless and dedicated work.
![image](https://user-images.githubusercontent.com/50471866/186602230-c31f708f-cf2a-474e-af1a-2340c478d5d8.png)
![1](https://user-images.githubusercontent.com/50471866/186605433-782892f4-74b8-4e5b-a69c-04f683db1e16.jpg)

**Comment by TsingZ0** [comment]
HI, @Mangata1 

Thanks for your suggestions! 

According to the authors mentioned in FedDyn's [paper](https://openreview.net/pdf?id=B7v4QMR6Z9w):
![image](https://user-images.githubusercontent.com/24207672/186883518-56c493b6-945e-4043-a85a-1b2caf1b8fcd.png)
the state is calculated by  $h^t=h^{t-1}-\alpha \frac{1}{m} (\sum_{k \in \mathcal{P}_t} (\theta^t_k-\theta^{t-1}))$.

On the other hand, if $|\mathcal{P}_t|$ becomes large, the magnitude of $\sum_{k \in \mathcal{P}_t} \theta^t_k$ will becomes larger than that of $\theta^{t-1}$.

**Comment by Mangata1** [comment]
You are right. Thanks for your reply！
