### ISSUE TITLE
The implement of APFL is quite different from the paper and the source code provided by the author.

### ISSUE THREAD

**Issue by sc1101** [TsingZ0/PFL-Non-IID#30]
Hello, I find that the implement of APFL in your platform is quite different from the paper and the source code provided by the author.

For example, there exists some extra code that APFL doesn't have, and it seems that you miss the code of updating alpha.

Can you check it?

Thank you.

**Comment by TsingZ0** [comment]
Hi, @sc1101 

I implemented APFL following [FedRep's official code](https://github.com/lgcollins/FedRep/blob/main/main_apfl.py) :-)

**Comment by TsingZ0** [comment]
I have updated the code for APFL, please check it.

**Comment by sc1101** [comment]
> I have updated the code for APFL, please check it.

Hi, I think it's perfect now, thank you.
