### ISSUE TITLE
About the results...

### ISSUE THREAD

**Issue by Bhongcheng** [TsingZ0/PFL-Non-IID#32]
I have tried some algorithm, but find the results are not much better than FedAvg. Do you have run these codes and what are your results like? Could you provide them and the hyper-parameters? 
    Best regards!

**Comment by TsingZ0** [comment]
Hi, @Bhongcheng 

I also use this code for my experiments. In the heterogeneous settings, all the personalized FL methods obviously outperform FedAvg (e.g., 10%-20% in test accuracy). 

In my experiments, I fix some parameters for settings, so the hyper-parameters tuned by myself may be not suitable in your generated settings.

**Comment by Bhongcheng** [comment]
Thank you

**Comment by Fruit0218** [comment]
你好，我也遇到了相同的问题，目前在测试pFedMe，也就是莫洛包络的个性化联邦学习，我发现精度并没有比FedAvg高多少，甚至会和FedAvg齐平，我检查了很多遍算法逻辑，都没发现什么问题（目前唯一可能出现问题的是算法中的参数传递过程，比如一些参数没有copy.deepcopy等，但应该不会犯这种低级错误），超参数我也在调整。所以想询问您关于这个问题的信息，可以吗？

**Comment by Fruit0218** [comment]
> ```
> I have tried some algorithm, but find the results are not much better than FedAvg. Do you have run these codes and what are your results like? Could you provide them and the hyper-parameters? 
> Best regards! 
> ```

你好，我也遇到了相同的问题，目前在测试pFedMe，也就是莫洛包络的个性化联邦学习，我发现精度并没有比FedAvg高多少，甚至会和FedAvg齐平，我检查了很多遍算法逻辑，都没发现什么问题（目前唯一可能出现问题的是算法中的参数传递过程，比如一些参数没有copy.deepcopy等，但应该不会犯这种低级错误），超参数我也在调整。所以想询问您关于这个问题的信息，可以吗？
