### ISSUE TITLE
About the FedRod

### ISSUE THREAD

**Issue by Bhongcheng** [TsingZ0/PFL-Non-IID#33]
My friend, could you please tell me that if this algorithm works in your experiments, compared with baseline(Fedavg and Local), and how much it can improve?  Best regards.

**Comment by TsingZ0** [comment]
Example setting: Non-IID and unbalanced (set partition == "dir" when generating dataset), Tiny-ImageNet, ResNet-18, 20 clients full participation

run 
```
python -u main.py -t 3 -jr 0.1 -rjr 1 -lr 0.1 -lbs 10 -ls 1 -nc 20 -nb 200 -data Tiny-imagenet-0.1 -m resnet -algo FedAvg -did 6
python -u main.py -t 3 -jr 0.1 -rjr 1 -lr 0.1 -lbs 10 -ls 1 -nc 20 -nb 200 -data Tiny-imagenet-0.1 -m resnet -algo FedROD -did 7
```

get test accuracy: FedAvg 19.45%, FedRoD 37.99%

**Comment by Bhongcheng** [comment]
Thank you for your reply!
I try these algorithm with cifar-10(dir and pat) and simple CNN model, bur find the result of fedavg is nearly the best...

**Comment by TsingZ0** [comment]
In practice, not all algorithms outperform others in all settings.
