### ISSUE TITLE
The Code of FedMTL Seems Wrong.

### ISSUE THREAD

**Issue by sc1101** [TsingZ0/PFL-Non-IID#34]
@TsingZ0 Hi, my friend, 

According to Readme, the code of FedMTL is refered to [Federated multi-task learning](https://arxiv.org/abs/1705.10467) NeurIPS 2017, which is called MOCHA in the paper.  However, I read the paper and the code offered by the author, it's quite different from your code.

Can you check it?

Thank you very much.

**Comment by TsingZ0** [comment]
Hi, @sc1101 

You are right. The key algorithm provided by [Federated multi-task learning](https://arxiv.org/abs/1705.10467) NeurIPS 2017 is called MOCHA not FedMTL. In this platform, FedMTL is not MOCHA either. Thje code of FedMTL is mainly related to Equation (1) and Equation (2) in this paper. 

I implement the code of FedMTL based on FedRep's official code: https://github.com/lgcollins/FedRep/blob/main/main_mtl.py

**Comment by sc1101** [comment]
OK, fine. But it would be better if your platform contained MOCHA.
