### ISSUE TITLE
About the FedBABU

### ISSUE THREAD

**Issue by Bhongcheng** [TsingZ0/PFL-Non-IID#37]
May I ask one question about the code?
You freeze the gratitude of the model's predictor.
![image](https://user-images.githubusercontent.com/90205287/192135561-321fe044-d8ad-4b9e-92b9-6fc91274042b.png)
I wonder whether the following code is necessary since the predictor of all clients will not be changed.
![image](https://user-images.githubusercontent.com/90205287/192135704-8d3359e1-dc7e-4996-967f-3a762a7420ca.png)
Thanks for your help

**Comment by TsingZ0** [comment]
During the federated learning process, each client uploads and downloads only the `base` part. From the communication view, this code is necessary for implementing FedBABU.

**Comment by Bhongcheng** [comment]
Really thank you!
