### ISSUE TITLE
about the "balanced_softmax_loss" in FedROD

### ISSUE THREAD

**Issue by Bhongcheng** [TsingZ0/PFL-Non-IID#40]
![image](https://user-images.githubusercontent.com/90205287/198589029-c4313068-08e5-4160-868b-f8290bd922b2.png)
”sample_per_class: A int tensor of size [no of classes]“
Maybe the value of it is the num instead of proportion?

**Comment by TsingZ0** [comment]
Thank you for your advice! I have revised it in the latest version :-)
