### ISSUE TITLE
local variable 'server' referenced before assignment

### ISSUE THREAD

**Issue by azalahmadkhan** [TsingZ0/PFL-Non-IID#41]
`!python main.py -data mnist -m cnn -algo fedfomo -gr 200 -lr 0.05 -jr 5.0 -tth 500`

On running above line on google colab I am getting below shown error

==================================================
Algorithm: fedfomo
Local batch size: 10
Local steps: 1
Local learing rate: 0.05
Total number of clients: 20
Clients join in each round: 5.0
Client drop rate: 0.0
Time select: False
Time threthold: 500.0
Global rounds: 200
Running times: 1
Dataset: mnist
Local model: cnn
Using device: cuda
Cuda device id: 0
==================================================

============= Running time: 0th =============
Creating server and clients ...
Traceback (most recent call last):
  File "main.py", line 307, in <module>
    run(args)
  File "main.py", line 171, in run
    server.train()
UnboundLocalError: local variable 'server' referenced before assignment

**Comment by TsingZ0** [comment]
I notice that the line number in the Traceback is not in line with the code in the current version. 
Did you use the latest code?

**Comment by azalahmadkhan** [comment]
No, this wasn't using the latest one.

**Comment by TsingZ0** [comment]
Could you provide more details about the modified `main.py` ?

**Comment by azalahmadkhan** [comment]
I am getting this error in the latest version of your code without modification.

`==================================================
Algorithm: fedfomo
Local batch size: 10
Local steps: 1
Local learing rate: 0.05
Total number of clients: 20
Clients join in each round: 5.0
Client drop rate: 0.0
Time select: False
Time threthold: 500.0
Global rounds: 200
Running times: 1
Dataset: mnist
Local model: cnn
Using device: cuda
Cuda device id: 0
==================================================

============= Running time: 0th =============
Creating server and clients ...
Traceback (most recent call last):
  File "main.py", line 358, in <module>
    run(args)
  File "main.py", line 216, in run
    raise NotImplementedError
NotImplementedError`

**Comment by TsingZ0** [comment]
Please use "FedFomo" instead of "fedfomo". All the inputs of this platform are case-sensitive.

**Comment by azalahmadkhan** [comment]
I am again facing some issues. Sorry for disturbing again. A few days back library used to work fine.

Now I am getting this -
==================================================
Algorithm: FedFomo
Local batch size: 10
Local steps: 1
Local learing rate: 0.05
Total number of clients: 20
Clients join in each round: 5.0
Client drop rate: 0.0
Time select: False
Time threthold: 500.0
Global rounds: 200
Running times: 1
Dataset: fmnist
Local model: cnn
Using device: cuda
Cuda device id: 0
==================================================

============= Running time: 0th =============
Creating server and clients ...

Join ratio / total clients: 5.0 / 20
Finished creating server and clients.
Traceback (most recent call last):
  File "main.py", line 358, in <module>
    run(args)
  File "main.py", line 218, in run
    server.train()
  File "/content/PFL-Non-IID/system/flcore/servers/serverfomo.py", line 29, in train
    self.selected_clients = self.select_clients()
  File "/content/PFL-Non-IID/system/flcore/servers/serverbase.py", line 80, in select_clients
    selected_clients = list(np.random.choice(self.clients, self.join_clients, replace=False))
  File "mtrand.pyx", line 965, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'

**Comment by TsingZ0** [comment]
Did you use the Python environment in `env_linux.yaml` ?
