### ISSUE TITLE
model aggregate question

### ISSUE THREAD

**Issue by DashingJ-82** [TsingZ0/PFL-Non-IID#43]
def aggregate_parameters(self):
        assert (len(self.uploaded_models) > 0)  # re

        self.global_model = copy.deepcopy(self.uploaded_models[0])
        for param in self.global_model.parameters():
            param.data.zero_()
            
        for w, client_model in zip(self.uploaded_weights, self.uploaded_models):
            self.add_parameters(w, client_model)

    def add_parameters(self, w, client_model):
        for server_param, client_param in zip(self.global_model.parameters(), client_model.parameters()):
            server_param.data += client_param.data.clone() * w

===========
in this model, I don't know how to pass the global model from the previous round to the next round.
My point of confusion is that I see the accumulation of weights and parameters, but not the passing of the final model parameters to the global model.
Can you help me with my questions?

**Comment by TsingZ0** [comment]
`self.global_model.parameters()` is a reference rather than a copy, `add_parameters()` modifies the parameter values in the global model in place.

**Comment by DashingJ-82** [comment]
def aggregate_parameters(self):
        assert (len(self.uploaded_models) > 0)  # 

        self.global_model = copy.deepcopy(self.uploaded_models[0])
        for param in self.global_model.parameters():
            param.data.zero_()
————————————————————————————————————————
I see this and don't particularly understand why self.global_model = copy.deepcopy(self.uploaded_models[0]) is executed (as it is cleared later), can you explain it simply

**Comment by TsingZ0** [comment]
This way, we can obtain an "empty" model with only the architecture. 

You can also use the `model.load_state_dict()` API in PyTorch. 

`copy.deepcopy()` is a more proper means, if the `global_model` architectures are different among communication iterations or if you want to aggregate other client modules besides the backbone model using the `aggregate_parameters()` API. 

The architecture of the `self.global_model` can be dynamic with different `self.uploaded_models[0]`.
