### ISSUE TITLE
About FedProto: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by daishu-li** [TsingZ0/PFL-Non-IID#44]
![image](https://user-images.githubusercontent.com/74223978/202171607-e55f69b9-3b74-40b5-8e8d-a282bb817122.png)
When I run FedProto, I meet this problem shown in the picture. 

May I please  you help me deal with this trouble ? Thank you !!!

**Comment by TsingZ0** [comment]
Thank you for your comments! I have uploaded the latest version :-)
