### ISSUE TITLE
FedPer client

### ISSUE THREAD

**Issue by DashingJ-82** [TsingZ0/PFL-Non-IID#45]
Hi, I have recently finished reading FedPer and FedRep. When I was reading the code, I found that FedPer's client code uploads the whole model, not the base model, which is different from FedRep's code, is it designed this way?

**Comment by TsingZ0** [comment]
Please check the code in https://github.com/TsingZ0/PFL-Non-IID/blob/master/system/flcore/servers/serverper.py#L61, only `client.model.base` is uploaded to the server.

**Comment by DashingJ-82** [comment]
yeah, I have see it.I don't see FedPer training for the head in the experiments, is it because there is no need to train for the head alone?

**Comment by TsingZ0** [comment]
Please check the code at https://github.com/TsingZ0/PFL-Non-IID/blob/master/system/flcore/clients/clientper.py#L14, all the parameters in the model (including the base and head). Note that I call "head" as "predictor" in this platform.
