### ISSUE TITLE
Data_utils

### ISSUE THREAD

**Issue by DashingJ-82** [TsingZ0/PFL-Non-IID#48]

**Comment by DashingJ-82** [comment]
def get_random_batch_sample(data_x, data_y, batch_size):
    num_parts = len(data_x)//batch_size + 1
    if(len(data_x) > batch_size):
        batch_idx = np.random.choice(list(range(num_parts + 1)))
        sample_index = batch_idx*batch_size
        if(sample_index + batch_size > len(data_x)):
            return (data_x[sample_index:], data_y[sample_index:])
        else:
            return (data_x[sample_index: sample_index+batch_size], data_y[sample_index: sample_index+batch_size])
    else:
        return (data_x, data_y)
 
 in this function, if the data_x = 32 and batch_size = 16, the batch_idx may be 3, so that the sample_index = 48. In this case, may cause array out-of-bounds.

**Comment by TsingZ0** [comment]
This Python method is out of use, and I have removed it in the current version :-)

**Comment by DashingJ-82** [comment]
thanks
