### ISSUE TITLE
About the random seed setting

### ISSUE THREAD

**Issue by Mangata1** [TsingZ0/PFL-Non-IID#49]
Hello @TsingZ0 ,
Thank you very much for the nice work. I have a small problem with the code, I find that when I run it multiple times with the same parameters I get variable results, I think it may be that the random seed is somewhere forgotten to set

**Comment by Mangata1** [comment]
I've had a brief look at the code and I think it may be that the random seeds in the device selection  are not fixed.

**Comment by TsingZ0** [comment]
Hi @Mangata1, I only set the seed for PyTorch. Please see https://github.com/TsingZ0/PFL-Non-IID/blob/1cd6dbb904468eb54afe1e1673c96ba792a41cf1/system/main.py#L46

Running the same Method multiple times with random seeds and then obtaining the mean and standard deviation of multiple results is a widely adopted way to report the results in papers.

**Comment by Mangata1** [comment]
Good work! Thansk for your reply.
