### ISSUE TITLE
一些关于fedfomo的问题

### ISSUE THREAD

**Issue by P1nder** [TsingZ0/PFL-Non-IID#52]
一，在论文里，在client端进行聚合的时候公式是这样的，
![1673180966310](https://user-images.githubusercontent.com/45331174/211196106-a06ee16a-f46f-4b06-b898-20e0cb5da988.png)
应该是client自己的模型加上权重乘以received model与自己model相减的差值，
但是在代码里面感觉不是这样的，是我理解的问题吗还是您的代码有出入呢
二，我想请教一下在计算权重时，client自身model的权重您是不是没有算
三，在给客户发送model的时候，您在代码里的做法是对于这一轮被选中的client，在他们的P矩阵中，仅仅只在上一轮给server上传model的那些客户里选择topk 个用户的模型，但不应该是在所有的客户里面选topk个模型吗，为什么只在上一轮给server上传模型的那些客户里面选呢，也就是self.P[client.id][self.uploaded_ids]这里

以上，因为看到您是国人，就不用英文了（英文有些辣鸡），来跟您请教一下这些问题，代码写得挺好的，看了好几篇在这个框架下复现的代码了，如果真的存在上面这些问题，也希望您能修改修改代码，如果是我理解的问题，欢迎一起学术交流呀

**Comment by TsingZ0** [comment]
对于（一）：根据原文，w_n的和属于{0,1}，分两种情况：（1）w_n的和 == 0，此时因为len(weights)==0，所以不执行aggregate_parameters中的add_parameters。（2）w_n的和 == 1，此时，你提到的式子可以写成
![image](https://user-images.githubusercontent.com/24207672/217980288-c5664c13-8596-41c8-9bb8-00e2113f7925.png)
正如aggregate_parameters计算的那样

对于（二）：自身model若包含在received_model中，则计算；若不在，则根据（一）在w_n的和 == 0时，不用其他模型更新自己，自身model的权重为1，在w_n的和 == 1时，自身model被其他模型的和覆盖。

对于（三）：已经在新版代码中修正。由于我平时跑代码的时候都是设置M==N==K，所以没发现问题，感谢！

**Comment by P1nder** [comment]
谢谢你的耐心指教！
