### ISSUE TITLE
Second-order gradient for Per-FedAvg:  Personalized Federated Learning with Theoretical Guarantees: A Model-Agnostic Meta-Learning Approach?

### ISSUE THREAD

**Issue by huiminzeng** [TsingZ0/PFL-Non-IID#54]
Hello, thank you very much for sharing the code! May I ask a question about the implementation of Per-FedAvg?

I think in the original paper, they used second-order gradients to compute the meta update in the MAML framework. However, I am not sure how this is implemented in this repo?

In particular, I am looking at this function: https://github.com/TsingZ0/PFL-Non-IID/blob/master/system/flcore/clients/clientperavg.py#L22. But I feel the implementation is kind of different from the original paper. Not sure if this is the right place to look?

Thank you very much!

**Comment by TsingZ0** [comment]
`Step 1` obtains a temp model $w - \alpha \nabla f_i(w)$. 

`Step 2` computes Eq. (5). 

[`Line 72`](https://github.com/TsingZ0/PFL-Non-IID/blob/master/system/flcore/clients/clientperavg.py#L72) computes Eq. (7).
