### ISSUE TITLE
uploaded_ids[]这个数组是不是忘了更新

### ISSUE THREAD

**Issue by P1nder** [TsingZ0/PFL-Non-IID#55]
在server端的self.receive_models()中，是不是应该对self.uploaded_ids[]这个数组进行更新，好像这个数组一直没有更新，是不是应该在server端的receive_models(）这个函数中添加 self.uploaded_ids.append(client.id) ？

**Comment by TsingZ0** [comment]
具体是哪行代码？如果某个算法用不到uploaded_ids这个数组的话，就没必要更新的

**Comment by P1nder** [comment]
看到你更新了代码，那就没问题了，如果不加self.uploaded_ids.append(client.id) 的话，在FedFomo方法里会出bug
