### ISSUE TITLE
Questions about the ditto algorithm

### ISSUE THREAD

**Issue by hacker-jerry** [TsingZ0/PFL-Non-IID#57]
Hi author, I would like to ask about the ditto algorithm part of this framework, why is ptrain (personalized Train) done here first and only then the global model is updated? 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/57279550/221208288-bf3fc299-42ec-4d51-86e6-c98747970598.png">
It is in `servers/serverditto.py`.
In the paper, the ptrain process relies on the updated global model weights as follows:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/57279550/221208095-5a5de492-72a1-4fc7-bcf5-eba2768915a1.png">
Please check whether you have made any mistakes. Thank you.

**Comment by TsingZ0** [comment]
Ditto uses the old global model $w^t$ for personalized model updating. I run `client.ptrain()` first to save extra global model storage costs. At this time, `client.model` is the old global model. If you run `client.train()` first, `client.model` is updated, and you need to create another variable to keep the old global model on the client for personalized model updating in `client.ptrain()`.

**Comment by hacker-jerry** [comment]
Thanks Tsing, I got the formula wrong, sorry ~
