### ISSUE TITLE
好多server.py文件中都注释掉了多线程代码，改为串行执行本地client训练，请问为什么呢？多线程会有负面影响吗

### ISSUE THREAD

**Issue by NJU-TJL** [TsingZ0/PFL-Non-IID#61]
多线程具体代码为：
```
            threads = [Thread(target=client.train)
                       for client in self.selected_clients]
            [t.start() for t in threads]
            [t.join() for t in threads]
```
请问这里多线程会有负面影响吗？

**Comment by TsingZ0** [comment]
Python中的GIL锁使得其执行多线程的效果和循环差不多，但缺需要额外的多线程维护开销，所以就注释掉了，作为大家的一种可选项。真正需要实现并行的话，可以通过多进程实现。

**Comment by NJU-TJL** [comment]
> Python中的GIL锁使得其执行多线程的效果和循环差不多，但缺需要额外的多线程维护开销，所以就注释掉了，作为大家的一种可选项。真正需要实现并行的话，可以通过多进程实现。

在我这边跑起来还是用Thread多线程会快很多，可能这个跟机器有关系。感谢解答！
