### ISSUE TITLE
Wandb.ai

### ISSUE THREAD

**Issue by Bhongcheng** [TsingZ0/PFL-Non-IID#62]
我好久前就关注你（的代码）了，恭喜你中了2023AAAI的论文呐，衷心为你感到高兴（是不是有点假哈哈）。
你知道wandb这个在线可视化结果的网站吗？我在别人的代码里经常看到，感觉蛮好用的。你是否有精力愿意在这个代码仓库中实现用wandb来展现结果呢（对不起，我太菜了）？
祝好

**Comment by TsingZ0** [comment]
算法模拟之外的其他可拓展功能，可以自行实现的。由于我个人精力有限，如果您愿意提交PR来实现这一功能，也是非常欢迎的
