### ISSUE TITLE
Potential Issue In PerAvg Server

### ISSUE THREAD

**Issue by cj-mclaughlin** [TsingZ0/PFL-Non-IID#67]
Hello, thanks for providing this repository.

I was modifying the PerAvg server and found that it makes two separate calls to train() (see below).

Is this intentional? I know the client-optimization has two separate internal steps to get the meta-gradient, but I do not see why the server would have twice as many calls to the train function.

https://github.com/TsingZ0/PFL-Non-IID/blob/3b2579a2a15f0fa066bd3779e14cfba42688b242/system/flcore/servers/serverperavg.py#L31-L33

**Comment by TsingZ0** [comment]
Please refer to #59 .
