### ISSUE TITLE
有一些算法的客户端的send_models方法是不是应该需要被重写

### ISSUE THREAD

**Issue by P1nder** [TsingZ0/PFL-Non-IID#69]
存在一个问题就是，在FedRep这个算法里，在每轮通讯开始时，算法中server会先采样一些客户，然后只给这些clients 发送model。
论文里是这样写的，如下
![image](https://user-images.githubusercontent.com/45331174/228282176-0690c992-b180-427e-b399-22f33e1a0f53.png)
所以是不是应该如在serverphp中的重写方法一样，只给self.selected_clients发送模型呢

**Comment by TsingZ0** [comment]
从训练的角度来说，每一轮只给一部分客户机发送模型和给所有客户机发送模型，没有区别，因为这一轮没被选中的客户机，只有在它被选中的时候才训练，而那时候，它会收到最新的模型。

从测试的角度来说，由于不是所有论文都采用同一种测试方式，为了公平起见，该平台采用了一种通用的测试方式。已修改FedPHP代码
