### ISSUE TITLE
环境配置的问题

### ISSUE THREAD

**Issue by minghub1** [TsingZ0/PFL-Non-IID#70]
为什么按照Readme.md文件中的命令conda env create -f env_cuda_116.yaml 会卡在solving environment那边很久，并且最终显示失败

**Comment by LengXinlin** [comment]
我差不多也是这个情况，加个好友讨论一下？

**Comment by BIGWJZ** [comment]
按照他这个yaml大概率配不出来环境，我直接把它里面用的手动install了一下就能跑了

**Comment by TsingZ0** [comment]
环境配置的话，yaml文件只是一种参考，我也只在自己的机器上测试过，主要是起到一个参考作用。如果自动安装不行的话，还是按照 @BIGWJZ 的做法进行手动安装吧

**Comment by zingjk** [comment]
> 按照他这个yaml大概率配不出来环境，我直接把它里面用的手动install了一下就能跑了

他这个环境就建立一个虚拟环境然后一个个装就可以了么？ 不管版本啥的么？我今天装完好像有点问题，求大佬解答！
