### ISSUE TITLE
SCAFFOLD Optimizer doesn't work

### ISSUE THREAD

**Issue by Codefmeister** [TsingZ0/PFL-Non-IID#72]
Thanks for your excellent job! 
I train the scaffold on the Cifar10 dataset. Each epoch it will return the same value, indicating there is no update on the model parameters.
Do you have the same questions?

**Comment by TsingZ0** [comment]
This problem did happen. I have fixed it. Please use the latest version.

**Comment by zingjk** [comment]
help !!! when I set parameters as follow, the algorithm doesn't work.
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/88484504/131f12db-1e96-4b64-8ddf-1598bb5e1ab5)
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/88484504/04f00ff1-afc6-4bb4-bc21-0aead9214df9)
