### ISSUE TITLE
关于ditto的问题

### ISSUE THREAD

**Issue by minghub1** [TsingZ0/PFL-Non-IID#73]
在Ditto算法中，每次client对server只是返回梯度，但是在这里的代码中，返回了整个模型的参数，我想请问一下这是为什么

**Comment by TsingZ0** [comment]
由于server具有旧的global model，而且每一次迭代，客户机都以该global model进行模型参数初始化，所以server获得梯度后，也可以通过计算获得每个客户机的模型参数，这是等价的。从现有文献来看，传输整个模型的这种说法更常见，于是本平台就按照这种传输方式以实现各个算法实现上具有统一的接口

**Comment by minghub1** [comment]
另外我还记得 FedBN 采取的是部分参数和主机共享，自己保留一部分，这个在代码里是不是没有体现出来
