### ISSUE TITLE
例子中的精度好高呀

### ISSUE THREAD

**Issue by RealRui** [TsingZ0/PFL-Non-IID#77]
cd ./system
python main.py -data mnist -m cnn -algo FedAvg -gr 2500 -did 0 -go cnn # for FedAvg and MNIST

上来就0.9978了

**Comment by TsingZ0** [comment]
因为MNIST数据集上的任务比较简单

**Comment by 3256638369** [comment]
是的，我运行cifar数据集,准确率只有50左右，请问有什么办法提高？

**Comment by xxdznl** [comment]
例子2000轮只有0.9874
