### ISSUE TITLE
About the placement of evaluate() in personalized FL.

### ISSUE THREAD

**Issue by leondada** [TsingZ0/PFL-Non-IID#78]
Hi, I notice that in your code, the evaluation is performed after sending the aggregated model to the client, which confuses me. 
In standard FL, such as FedAvg, our goal is a global model, so testing after sending the models is not a problem. However, in PFL, I see in papers such as Ditto that the model is tested after training process on the client side, which is inconsistent with the code.  Therefore, should the "self.evaluate()" in the server code be placed after the "client.train()"?

**Comment by youpengl** [comment]
My understanding is that the purpose of self.evaluate() is to test the performance of the global model ((in a PFL fashion) obtained at the beginning of each round (or at the end of the previous round) .

**Comment by leondada** [comment]
@youpengl  Thank you for your reply. I agree that the function is used to test the performance of the global model. However, I didn't see any additional testing for personalized models in the code (maybe I missed it), so I'm not sure what the author used for testing.

**Comment by youpengl** [comment]
@leondada https://github.com/TsingZ0/PFL-Non-IID/blob/cc7f2a01aa2b7cef6a584f3e1835be736f0c9039/system/flcore/servers/serverditto.py#L46

**Comment by leondada** [comment]
got it!
