### ISSUE TITLE
[Dataset Question] Can PFL-Non-IID integrate the VOC dataset?

### ISSUE THREAD

**Issue by hacker-jerry** [TsingZ0/PFL-Non-IID#8]
Hi, I want to integrate Yolo model in this project and use VOC dataset for training. Is it possible?

The VOC dataset structure is like this:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/57279550/164166559-ba2c6141-8c67-4445-ad8d-e6f858372a75.png">

Waiting for your reply, thanks!

**Comment by hacker-jerry** [comment]
For example, I load VOC dataset into trainloader(with all images transform)

```python
class Transform(object):

    def __init__(self, min_size=600, max_size=1000):
        self.min_size = min_size
        self.max_size = max_size

    def __call__(self, in_data):
        img, bbox, label = in_data
        _, H, W = img.shape
        img = preprocess(img, self.min_size, self.max_size)
        _, o_H, o_W = img.shape
        scale = o_H / H
        bbox = util.resize_bbox(bbox, (H, W), (o_H, o_W))

        # horizontally flip
        img, params = util.random_flip(
            img, x_random=True, return_param=True)
        bbox = util.flip_bbox(
            bbox, (o_H, o_W), x_flip=params['x_flip'])

        print('Transform a pic\n')

        return img, bbox, label, scale


class VOCDataset:
    def __init__(self):
        
        self.db = VOCBboxDataset(cfg.DATA_PATH)#训练数据路径
        self.tsf = Transform(cfg.MIN_SIZE, cfg.MAX_SIZE)

    def __getitem__(self, idx):
        ori_img, bbox, label, difficult = self.db.get_example(idx)

        img, bbox, label, scale = self.tsf((ori_img, bbox, label))
        # TODO: check whose stride is negative to fix this instead copy all
        # some of the strides of a given numpy array are negative.
        return img.copy(), bbox.copy(), label.copy(), scale

    def __len__(self):
        return len(self.db)


class VOCTestDataset:
    def __init__(self,  split='test', use_difficult=True):
        
        self.db = VOCBboxDataset(cfg.TEST_PATH, split=split, use_difficult=use_difficult)

    def __getitem__(self, idx):
        ori_img, bbox, label, difficult = self.db.get_example(idx)
        img = preprocess(ori_img)
        return img, ori_img.shape[1:], bbox, label, difficult

    def __len__(self):
        return len(self.db)
```

<img width="655" alt="image" src="https://user-images.githubusercontent.com/57279550/164206199-91ab60c8-5f71-4690-8916-57b7a1142e98.png">

But when running to this step:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/57279550/164206787-32bc0c78-c53f-4b28-b146-ef4c5d770360.png">

Program Error：
<img width="918" alt="image" src="https://user-images.githubusercontent.com/57279550/164206985-51fe8b46-d023-468d-96bf-8ccd4a20e797.png">

It seems like the data each sensors are not equal size. Can that dataloader be used in here? Do you know how to solve this problem?

Thanks a lot!

**Comment by Fruit0218** [comment]
> For example, I load VOC dataset into trainloader(with all images transform)
> 
> ```python
> class Transform(object):
> 
>     def __init__(self, min_size=600, max_size=1000):
>         self.min_size = min_size
>         self.max_size = max_size
> 
>     def __call__(self, in_data):
>         img, bbox, label = in_data
>         _, H, W = img.shape
>         img = preprocess(img, self.min_size, self.max_size)
>         _, o_H, o_W = img.shape
>         scale = o_H / H
>         bbox = util.resize_bbox(bbox, (H, W), (o_H, o_W))
> 
>         # horizontally flip
>         img, params = util.random_flip(
>             img, x_random=True, return_param=True)
>         bbox = util.flip_bbox(
>             bbox, (o_H, o_W), x_flip=params['x_flip'])
> 
>         print('Transform a pic\n')
> 
>         return img, bbox, label, scale
> 
> 
> class VOCDataset:
>     def __init__(self):
>         
>         self.db = VOCBboxDataset(cfg.DATA_PATH)#训练数据路径
>         self.tsf = Transform(cfg.MIN_SIZE, cfg.MAX_SIZE)
> 
>     def __getitem__(self, idx):
>         ori_img, bbox, label, difficult = self.db.get_example(idx)
> 
>         img, bbox, label, scale = self.tsf((ori_img, bbox, label))
>         # TODO: check whose stride is negative to fix this instead copy all
>         # some of the strides of a given numpy array are negative.
>         return img.copy(), bbox.copy(), label.copy(), scale
> 
>     def __len__(self):
>         return len(self.db)
> 
> 
> class VOCTestDataset:
>     def __init__(self,  split='test', use_difficult=True):
>         
>         self.db = VOCBboxDataset(cfg.TEST_PATH, split=split, use_difficult=use_difficult)
> 
>     def __getitem__(self, idx):
>         ori_img, bbox, label, difficult = self.db.get_example(idx)
>         img = preprocess(ori_img)
>         return img, ori_img.shape[1:], bbox, label, difficult
> 
>     def __len__(self):
>         return len(self.db)
> ```
> 
> <img alt="image" width="655" src="https://user-images.githubusercontent.com/57279550/164206199-91ab60c8-5f71-4690-8916-57b7a1142e98.png">
> 
> But when running to this step: <img alt="image" width="639" src="https://user-images.githubusercontent.com/57279550/164206787-32bc0c78-c53f-4b28-b146-ef4c5d770360.png">
> 
> Program Error： <img alt="image" width="918" src="https://user-images.githubusercontent.com/57279550/164206985-51fe8b46-d023-468d-96bf-8ccd4a20e797.png">
> 
> It seems like the data each sensors are not equal size. Can that dataloader be used in here? Do you know how to solve this problem?
> 
> Thanks a lot!

Did you succeed? I am currently working on federated learning for semantic segmentation tasks and want to implement personalized federated learning in it. The dataset I am using is cityscapes dataset, which I used for VOC before, and the model is deeplabv3+, but I found it a bit complicated, so I changed it to bisenetv2
