### ISSUE TITLE
I can't create environment with your command "conda env create -f env_cuda_116.yaml"

### ISSUE THREAD

**Issue by zmes40404** [TsingZ0/PFL-Non-IID#80]
您好，

首先非常感謝你的Contribution
我在嘗試執行你的程式碼時有遇到一些問題
我照您的指令 "conda env create -f env_cuda_102.yaml" 創建環境時顯示有"Package conflict"
所以導致"Solving Environment: faild"，環境無法創建成功

另外執行指令"conda env create -f env_cuda_116.yaml" 時會卡在"Solving Environment:"那邊，無法繼續創建環境
想請問我需要如何解決呢?
是需用手動安裝"env_cuda_102.yaml" or "env_cuda_116.yaml"檔案中的每一個packages嗎? 

非常期待與感謝您的耐心解答

OS System: Ubuntu 20.04
Virtual Environment: Miniconda3

**Comment by TsingZ0** [comment]
请先参考 #70 ，等我忙过这阵子会处理一下环境配置的问题

**Comment by TsingZ0** [comment]
In the latest version, I remove the conda-forge channel and reorder dependencies. Then, you can run `conda config --set channel_priority strict` before `conda env create -f env_cuda_116.yaml` to force the searching order. 

The updated `env_cuda_116.yaml` now worked for me.
