### ISSUE TITLE
FedMTL算法代码的运行似乎有问题

### ISSUE THREAD

**Issue by youngfish42** [TsingZ0/PFL-Non-IID#81]
当运行 --algorithm FedMTL 时，会提示变量 [self.W_glob](https://github.com/TsingZ0/PFL-Non-IID/blob/d904916dd0ec61f71e7055335421eab288651afe/system/flcore/clients/clientmtl.py#L95) 和 [self.omega](https://github.com/TsingZ0/PFL-Non-IID/blob/d904916dd0ec61f71e7055335421eab288651afe/system/flcore/clients/clientmtl.py#L102) 相关的错误

TypeError: 'NoneType' object does not support item assignment
TypeError: 'NoneType' object is not subscriptable

**Comment by TsingZ0** [comment]
已更新
