### ISSUE TITLE
Per-FedAvg算法

### ISSUE THREAD

**Issue by youngfish42** [TsingZ0/PFL-Non-IID#82]
[Per-FedAvg](https://github.com/TsingZ0/PFL-Non-IID/blob/34675e57e82e1976725c923802eedbd1bf9f3dfa/README.md?plain=1#L44)在本代码库中的名称经过排查，似乎是PerAvg，是否需要补充说明或替换算法名称？

**Comment by TsingZ0** [comment]
这个应该没问题吧，因为有些论文称Per-FedAvg为PerAvg
