### ISSUE TITLE
BUG in aggregate（Important）

### ISSUE THREAD

**Issue by harrylee999** [TsingZ0/PFL-Non-IID#84]
![image](https://user-images.githubusercontent.com/59381501/231441106-9c02d845-3ac1-4350-ac71-a94d504786d1.png)
你的聚合代码里bn层每轮这三个参数都没有聚合，每轮只是用了其中一个客户端的参数。这样如果选择了一个数据量少的客户端，会使模型的性能下降，且训练会变得不稳定甚至不收敛。我的建议是聚合那里改成用模型的state_dict遍历，不要用param.data。

**Comment by TsingZ0** [comment]
按照这些方法的论文描述来看，server端聚合是只聚合trainable model parameters（也就是他们论文中的W），running_mean和running_var等不属于trainable model parameters而是一种统计信息。这类信息如果不保留在本地而进行传输，岂不是直接就能知道数据（feature）分布信息了？因为我们还可以直接对 高斯分布N(running_mean, running_var) 进行采样，生成feature

**Comment by harrylee999** [comment]
既然mean和cov不能上传 那你聚合代码里的第一步就是self.global_model = copy.deepcopy(self.uploaded_models[0]) 把客户端的mean和cov copy给了global_model，这也不相当于传输了吗？这样global_model每次都是用的某个客户端的mean和cov，如果copy了一个分布非常bias的客户端，这样每轮评价global_model是不是不太合理？

**Comment by TsingZ0** [comment]
self.global_model = copy.deepcopy(self.uploaded_models[0])这个语句的目的不是复制信息的，而是复制了model structure，用于装载聚合得到的global model parameters，我们在这语句之后将所有参数置零了，详细请参考：https://github.com/TsingZ0/PFL-Non-IID/blob/master/system/flcore/servers/serverbase.py#L136。

每轮并不会使用server.global_model来进行inference，它只是一个存储模型参数的载体。server.evaluate()是在接收到global model parameters后的client.model上进行测试的。
