### ISSUE TITLE
About the Moon 

### ISSUE THREAD

**Issue by xxxyy95** [TsingZ0/PFL-Non-IID#86]
Hello, thank you for your awesome platform. I would like to ask if you have completed the Transformer Model of the two data sets of AG_News and Sogou_News? I want to use the Transformer-based Model to solve it with the Moon algorithm, but I find that the model is too large to be realized.

**Comment by TsingZ0** [comment]
The task of integrating Transformer-based models into this platform has been delayed due to my busy schedule in recent months. You are welcome to add them. :-)
