### ISSUE TITLE
关于sogouNews 

### ISSUE THREAD

**Issue by DashingJ-82** [TsingZ0/PFL-Non-IID#87]
你好，torch 1.11.0  下载sogouNews提示RuntimeError: Internal error: confirm_token was not found in Google drive link.
不知道作者是否可以用这个下载sogounews数据集呢

**Comment by TsingZ0** [comment]
之前尝试的早期版本pytorch=1.8.0是可以下载的，可以试试。或者手动下载，链接：https://drive.google.com/uc?export=download&id=0Bz8a_Dbh9QhbUkVqNEszd0pHaFE

**Comment by DashingJ-82** [comment]
好的 我试试看 感谢🙏
