### ISSUE TITLE
50客户端时运行SCAFFOLD存在问题

### ISSUE THREAD

**Issue by MirandaHe** [TsingZ0/PFL-Non-IID#88]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/105597549/235574391-ea2b5ecb-5afc-42a7-b394-204a68dbc005.png">
在dataset中更改为50客户端，超参数也设置为50，dir0.1环境下运行时出现问题，可以帮忙解答以下吗，十分感谢！！

**Comment by TsingZ0** [comment]
我这边跑起来没问题，可以提供更多细节吗？

**Comment by MirandaHe** [comment]
<img width="953" alt="1" src="https://user-images.githubusercontent.com/105597549/235578136-d871a90a-ee08-4e01-8b52-582514405750.png">
运行20个客户端时一切正常，但是改为50后出现错误

**Comment by MirandaHe** [comment]
<img width="953" alt="1" src="https://user-images.githubusercontent.com/105597549/235578136-d871a90a-ee08-4e01-8b52-582514405750.png">
运行20个客户端时一切正常，但是改为50后出现错误

**Comment by MirandaHe** [comment]
<img width="953" alt="1" src="https://user-images.githubusercontent.com/105597549/235578445-a218c6d9-3ed1-4422-92ab-56f481c23d7f.png">
设置为20个客户端时一切正常，但是SCAFFOLD改为50个后出现问题，请教您。

**Comment by TsingZ0** [comment]
请提供一下平台的超参数设置细节

**Comment by MirandaHe** [comment]
已经解决了！十分感谢！！！
