### ISSUE TITLE
question about local train

### ISSUE THREAD

**Issue by fengkoushangdeZZX** [TsingZ0/PFL-Non-IID#91]
您好，首先非常感谢您的精彩工作和开源精神，我在用您的库做实验时遇到了一个问题想向您请教。就是是我的客户端数据是noiid的，总的数据集有10类，但是每个客户端可能只有一部分标签类别，就是您展示的Dirichlet distribution这种情况，那么我每个客户端在本地训练的时候输出的类别是10类还是就输出这个客户端包含的类别呢？

**Comment by TsingZ0** [comment]
目前科研界主要考虑的问题是：每个客户机的本地训练任务都是一致的。比如您说的这种情况，每个客户机都是考虑10分类任务的。不然的话，就难以做完整模型的参数聚合了，比如输出层参数shape不同。

**Comment by fengkoushangdeZZX** [comment]
非常感谢您的解答，您的意思是每个客户机即使只有部分标签对应的样本，（比如客户端1包含标签类型1，3，4，6，总的标签类型是10类），他的输出层也是10类对吗？那这种情况那些不包含全部标签的客户端在训练过程中会对其他标签的训练产生影响吗？

**Comment by TsingZ0** [comment]
应该会的，这是一个很有意思的研究方向，期待您的工作！
