### ISSUE TITLE
FedProto

### ISSUE THREAD

**Issue by g1013271809** [TsingZ0/PFL-Non-IID#92]
请问 为什么FedProto的个性化evaluate test_metrics()方法 和其他算法的不一样
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/45585102/25cd46b9-42f5-4880-9a85-277c1987403f)
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/45585102/e19be225-679e-45ba-800d-5ea910c081a0)

**Comment by TsingZ0** [comment]
请参考[FedProto原文](https://arxiv.org/pdf/2105.00243.pdf)的Prototype-based model inference章节
