### ISSUE TITLE
关于数据集产生的问题

### ISSUE THREAD

**Issue by 3256638369** [TsingZ0/PFL-Non-IID#94]
非常感谢您的开源精神和巨大的贡献，我在运行产生数据集文件时会遇到IndexError: list index out of range的问题
![Q6FP%)N0%L@K 8VO X8Y3RT](https://github.com/TsingZ0/PFL-Non-IID/assets/102151616/84eff2ff-bab8-47dc-b343-c507d5879908)
在这里我将文件改成
![2_{KW28S}FP99BJNYXX%L4F](https://github.com/TsingZ0/PFL-Non-IID/assets/102151616/66c9144c-aac7-4956-8d3f-d516e3e20d97)
可以生成需要的原始数据集，但在训练集和测试集中没有文件，所以我想知道如何将数据集分成所需要的.npz格式文件。期待你的指点！

**Comment by liming-chang** [comment]
请问你在生成数据集的时候，代码能运行么？我在运行代码是缺少了一个模块，导致代码无法运行。
![image](https://github.com/TsingZ0/PFL-Non-IID/assets/53501467/a2a8aeff-2e1c-4b9e-9aa9-9ba2ed5ac602)
这是我下载的代码中出现错误的地方，其中，sklearn模块找不到。你的代码里有这个模块么？

**Comment by TsingZ0** [comment]
根据你提供的截图，猜测你是要在Cifar10上生成noniid balanced data。

在最新代码里，`python generate_cifar10.py noniid balance pat` 可以顺利执行。

其他noniid balanced data生成方式，目前该平台不支持，会报`NotImplementedError`错误。


此外， IndexError: list index out of range应该是输入格式不对，请参考 https://github.com/TsingZ0/PFL-Non-IID#examples-for-mnist

**Comment by GNPNB** [comment]
冒昧的打扰了，一楼我也遇到相同的问题了，请问你解决了嘛？

**Comment by GNPNB** [comment]
@3256638369 这个问题我解决了，你把原来的代码稍微修改一下即可，就可以得到你所需要的东西了，如下所示:
niid = True if len(sys.argv) > 1 and sys.argv[1] == "noniid" else False
    balance = True if len(sys.argv) > 2 and sys.argv[2] == "balance" else False
    partition = sys.argv[3] if len(sys.argv) > 3 and sys.argv[3] != "-" else None
希望可以帮你的忙。
