### ISSUE TITLE
FedAMP

### ISSUE THREAD

**Issue by g1013271809** [TsingZ0/PFL-Non-IID#95]
作者你好 我跑了一下FedAMP 发现和local的ACC 曲线一模一样 烦请你排查一下？

**Comment by TsingZ0** [comment]
你的超参数设置是什么样的

**Comment by g1013271809** [comment]
超参数都是1

**Comment by TsingZ0** [comment]
完整的超参数设置，或者说运行时输入的命令行？

**Comment by TsingZ0** [comment]
此外，请注意，由于FedAMP的本地模型是不会被全局模型覆盖的。如果你的超参数设置使得attention weights中当前客户机的权重为1，那训练效果就会类似于Local。FedAMP对超参数比较敏感，且在不同任务下具有不同最优超参数，请小心调参后使用。
